version: '3.7'
services:
    app:
        build: .
        restart: always
        volumes:
            - '/app/node_modules'
            - ./:/app
        ports:
            - 4200:4200
        command:
            ng serve --host 0.0.0.0 --poll 2
     